# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/twsnmp/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_x86_64.tar.gz"
      sha256 "a82ee2979060f4a619980ce0c3fe9c7cb83929b3bc53dee47ae7f1b83e4d0583"

      def install
        bin.install "hello-cli"
      end
    end
    on_arm do
      url "https://github.com/twsnmp/hello-cli/releases/download/v0.2.0/hello-cli_Darwin_arm64.tar.gz"
      sha256 "2804cce7890d85f7d7bd2bd81d44830f73101320a15d06d32c25365e420c0bbe"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/twsnmp/hello-cli/releases/download/v0.2.0/hello-cli_Linux_x86_64.tar.gz"
        sha256 "7adf4e29cb10f5c37bcfc1144a1454cde86e9558b788f523de3e6daaeee982ea"

        def install
          bin.install "hello-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/twsnmp/hello-cli/releases/download/v0.2.0/hello-cli_Linux_arm64.tar.gz"
        sha256 "85659cd8a0ca9099b718cba55c6b90bb99afd501d962951a9dd8aac7304014fe"

        def install
          bin.install "hello-cli"
        end
      end
    end
  end
end
