# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twlogeye < Formula
  desc ""
  homepage ""
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.5.0/twlogeye_darwin_amd64.tar.gz"
      sha256 "f52911e5ec93f81e685fa07929d9de3c4f2ffc747405ced4d041d7c3bc701185"

      define_method(:install) do
        bin.install "twlogeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.5.0/twlogeye_darwin_arm64.tar.gz"
      sha256 "1d58ebd2339adddb77cdc8780b1865f3245ebd885dea7bce1452e28fd00f336e"

      define_method(:install) do
        bin.install "twlogeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.5.0/twlogeye_linux_amd64.tar.gz"
      sha256 "86d4d9897b85ab97b92f139c59dce7e846c70168e6f62b4cb3999e383178fc96"
      define_method(:install) do
        bin.install "twlogeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.5.0/twlogeye_linux_arm64.tar.gz"
      sha256 "6b804ca4ab4114f05e970b79df676e31f7b983ccb53486cbd96593932d877d4c"
      define_method(:install) do
        bin.install "twlogeye"
      end
    end
  end
end
