# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twlogeye < Formula
  desc ""
  homepage ""
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.4.3/twlogeye_Darwin_x86_64.tar.gz"
      sha256 "e49b321b0a9bd2d4c7f06b83fc0cae096cfc9e44e262a0429e032c62a8224dcc"

      def install
        bin.install "twlogeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.4.3/twlogeye_Darwin_arm64.tar.gz"
      sha256 "7c635ee9342f46622c415958d32163eb8265e81d063da4ecd000dc080246c1ba"

      def install
        bin.install "twlogeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.4.3/twlogeye_Linux_x86_64.tar.gz"
      sha256 "f4b95271d858ad0e07b6ac6b3d215bb5a6f40d272d3a48c710f48fcae735f8bf"
      def install
        bin.install "twlogeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.4.3/twlogeye_Linux_arm64.tar.gz"
      sha256 "1a6715cfe5cdefa23a2802437502f7a797332e77d8d7956aa252951290812ede"
      def install
        bin.install "twlogeye"
      end
    end
  end
end
