# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twlogeye < Formula
  desc ""
  homepage ""
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.6.0/twlogeye_darwin_amd64.tar.gz"
      sha256 "d03a06fbce49a693bd124b303ec24706cf0cfcd7c8cc2e84c451537fad9a7019"

      define_method(:install) do
        bin.install "twlogeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.6.0/twlogeye_darwin_arm64.tar.gz"
      sha256 "07a632216f0db7f3cd5ab88e53b9e04a08a3c85e5dc10cf335c47501d8c67a9e"

      define_method(:install) do
        bin.install "twlogeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.6.0/twlogeye_linux_amd64.tar.gz"
      sha256 "71245c8d1143b9fcad466d863096f64818e360a2036b2a60298b97584367d88d"
      define_method(:install) do
        bin.install "twlogeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twlogeye/releases/download/v0.6.0/twlogeye_linux_arm64.tar.gz"
      sha256 "9ef5135c43902711854404a28e3081eedcd0aeaaa441b97e16932d32516769bb"
      define_method(:install) do
        bin.install "twlogeye"
      end
    end
  end
end
