# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twsla < Formula
  desc ""
  homepage ""
  version "1.17.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.1/twsla_Darwin_x86_64.tar.gz"
      sha256 "e8d339c1ed4a5c53ddd124bd3596d5ddc6432c46004b80838a48c54ca461adc6"

      def install
        bin.install "twsla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.1/twsla_Darwin_arm64.tar.gz"
      sha256 "76007b9f51f0dbb6763ed76ecf5d8019811a5e435544e9e7c3dec5b18e407e1f"

      def install
        bin.install "twsla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.1/twsla_Linux_x86_64.tar.gz"
      sha256 "06b1abb096774ff0557d7dff4ddc2c3ef2201d523c7e3108e22f968ce9c8bf09"
      def install
        bin.install "twsla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.1/twsla_Linux_arm64.tar.gz"
      sha256 "97d808cfd5612efea49c6ea8389f4a8ccef0cda4c4aa23e50c231b56204bc90a"
      def install
        bin.install "twsla"
      end
    end
  end
end
