# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twsla < Formula
  desc ""
  homepage ""
  version "1.21.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twsnmp/twsla/releases/download/v1.21.1/twsla_Darwin_x86_64.tar.gz"
      sha256 "41186b0269ed3b3736898eb65e7e3071819feca69b4901a5d94bbdb4ad781a20"

      define_method(:install) do
        bin.install "twsla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twsnmp/twsla/releases/download/v1.21.1/twsla_Darwin_arm64.tar.gz"
      sha256 "90e56f90530518fc303c1fdeb4dbeb821f20532cd3f4e75eed3cf8d34e761e53"

      define_method(:install) do
        bin.install "twsla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twsla/releases/download/v1.21.1/twsla_Linux_x86_64.tar.gz"
      sha256 "f67551e5d913d4284db74b5d29e07ef391b9f4ec696e7cdf7d70cf5ea7328d49"
      define_method(:install) do
        bin.install "twsla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twsla/releases/download/v1.21.1/twsla_Linux_arm64.tar.gz"
      sha256 "5ec30dd0d5cad688ab3769ee62681704a35079608cd8d556185fcfc9ff3dd974"
      define_method(:install) do
        bin.install "twsla"
      end
    end
  end
end
