# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twsla < Formula
  desc ""
  homepage ""
  version "1.17.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.0/twsla_Darwin_x86_64.tar.gz"
      sha256 "3e3cb740f86e2c1532ecb09263dfb2f8151aba44acc4f157a23234006279d432"

      def install
        bin.install "twsla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.0/twsla_Darwin_arm64.tar.gz"
      sha256 "af9867e8661fb0660e79f3a2ec8ac6ba2b33f471ea3e91c0ad187a12022d2cea"

      def install
        bin.install "twsla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.0/twsla_Linux_x86_64.tar.gz"
      sha256 "1dcb4ae066e640447c11ba0c2bb22a4d93dde6698a4650ca644e06e54dae0523"
      def install
        bin.install "twsla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twsnmp/twsla/releases/download/v1.17.0/twsla_Linux_arm64.tar.gz"
      sha256 "10051c5b349cbc93403485fff42f9e9d22c5635dbb754e832f6acf8a1643ad5e"
      def install
        bin.install "twsla"
      end
    end
  end
end
