# This file was generated by GoReleaser. DO NOT EDIT.
cask "twlogeye" do
  name "twlogeye"
  desc ""
  homepage ""
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twlogeye"

  on_macos do
    on_intel do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Darwin_x86_64.tar.gz"
      sha256 "c76b58f77748eb2f400f367d2a7735c9b958ea8e0c95e970273bb0ca7fa2354a"
    end
    on_arm do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Darwin_arm64.tar.gz"
      sha256 "3411048b482187135b5ec9976f93e588ed3f6b5da00508ef661404c14b2f585e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Linux_x86_64.tar.gz"
      sha256 "1a9e3bd3c082b2d19bf0e2ccb64a3890b881928a886248f2917500715ccb5457"
    end
    on_arm do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Linux_arm64.tar.gz"
      sha256 "c43f05ef37fa4126d6e812b79c0520a2f785c1dafdaf22806f00b9532bd7e8e3"
    end
  end

  # No zap stanza required
end
