# This file was generated by GoReleaser. DO NOT EDIT.
cask "twlogeye" do
  name "twlogeye"
  desc ""
  homepage ""
  version "0.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twlogeye"

  on_macos do
    on_intel do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Darwin_x86_64.tar.gz"
      sha256 "524221ca1c14e53f52755683915b847353d8b4c0bf67b274357f46d39ef3c13b"
    end
    on_arm do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Darwin_arm64.tar.gz"
      sha256 "cf2a1758db5cf7d7809b4d6da570f2f27ad96ee396c3de97f20d2ffc01d44078"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Linux_x86_64.tar.gz"
      sha256 "83ab35dc05695a8fa2981d6f6f261d1232755dc94ecb15b68895a481a1904d6e"
    end
    on_arm do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Linux_arm64.tar.gz"
      sha256 "66a124e9a7683025c9032c9d4624a9e0ea03f89dcd6aaca6c15c21d28c656787"
    end
  end

  # No zap stanza required
end
