# This file was generated by GoReleaser. DO NOT EDIT.
cask "twlogeye" do
  name "twlogeye"
  desc ""
  homepage ""
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twlogeye"

  on_macos do
    on_intel do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Darwin_x86_64.tar.gz"
      sha256 "e7f7da398aac1ab479d2d545d76eb6b61440c20fc46dcefaf7e6e2a66e52fdec"
    end
    on_arm do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Darwin_arm64.tar.gz"
      sha256 "1840cea5c9be4ab9c15e0bcf5ce346566e1289befdb34ecc341b5d1c89ae7e1d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Linux_x86_64.tar.gz"
      sha256 "1436a36141dc2e82db8d1a9da5e2b43934412e05480d66ae2dd143f262044be4"
    end
    on_arm do
      url "https://github.com/twsnmp/twlogeye/releases/download/v#{version}/twlogeye_Linux_arm64.tar.gz"
      sha256 "f0a7e87c89f40134dd8605f3e91593beaf3db0e740d39e5dbb882c76d9902666"
    end
  end

  # No zap stanza required
end
