# This file was generated by GoReleaser. DO NOT EDIT.
cask "twsla" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "0b0948dfd946732c704b00edb776ba2c72e598baa9296cdc782c93f0264f1e6e"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "967462fc573dda70092364c4e29a48ab54b6ffa4bf16ad3df4ad3e0dbf92ab8b"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "63cf82f8d75237b41e5745ac06fc00ac023c1d5f1a9ba59e6160b355249b5ad5"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c36302b4fc6140e78ef36a52c9df399d218c0a252bb3eff3da0208491538a76"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_linux_amd64.tar.gz"
    end
  end

  name "twsla"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twsla"

  # No zap stanza required
end
