# This file was generated by GoReleaser. DO NOT EDIT.
cask "twsla" do
  version "1.22.0"

  on_macos do
    on_intel do
      sha256 "07f24e786d14f88b3c0910ac7e8c63f5267ddec984bb9e7b22692bb7840ee799"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd14123f30e2830644fbc88a2f3c7b2372b4f6816179f917a71979bbca1ec658"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8fbf249e894bdc44144215b8197b530f045bcea2e61821df0aff2dd16a57345"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d16f8cc0e0b5ab865a637910568c6cbbae05655bf70099bbd5113a60cb88012"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_linux_arm64.tar.gz"
    end
  end

  name "twsla"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twsla"

  # No zap stanza required

end
