# This file was generated by GoReleaser. DO NOT EDIT.
cask "twsla" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "9553a01353c3f6161e6de026ffad3e088821b9514743561e504469a67dcfd79d"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f82fd5026b32bcc48941f177bd675fc8e9724495b4f131ddd389ff15956e76e"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a87915b91134f7486ff3d7d8092b00de2c569a86837d26afcecc95db25d4b39"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c2d2716f6ee1886b359800a45dbfe8cb8d6619985d7bd6921be5e601163c75c"
      url "https://github.com/twsnmp/twsla/releases/download/v#{version}/twsla_linux_amd64.tar.gz"
    end
  end

  name "twsla"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twsla"

  # No zap stanza required
end
